services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\NovalnetPaymentGateway:
        arguments:
            $options: []
        tags:
            - { name: pimcore_ecommerce.payment.provider, key: 'novalnet' }

    Pimcore\Bundle\EcommerceFrameworkBundle\NovalnetPaymentGateway\Installer:
        public: true
